export const ADMIN_ROUTE = '/admin'
export const MAIN_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const USER_ROUTE = '/userPage'
export const CREATE_ROUTE = '/createReview'